site_name: "Hackathon17"
theme: readthedocs
pages:
- Home: 'index.md'
- Schedule: 'schedule.md'
- "Edit docs": 'docs.md'
- "Training Material": training-material.md
#- "Tools and scrips": tools-and-scrips.md
